export const starterBooks = [
  {
    id: "book-atomic-habits",
    title: "Atomic Habits",
    author: "James Clear",
    category: "Self Growth",
    description:
      "A practical book on building small systems that compound into better habits.",
    notes:
      "Useful for routine design. Revisit the sections on identity-based habits.",
    pageCount: 320,
    progress: 72,
    status: "reading",
    rating: 5,
    isFavorite: true,
    createdAt: "2026-07-20T09:00:00.000Z",
    updatedAt: "2026-08-01T10:30:00.000Z",
  },
  {
    id: "book-deep-work",
    title: "Deep Work",
    author: "Cal Newport",
    category: "Productivity",
    description:
      "A strong argument for focus, concentration, and protecting attention.",
    notes: "Great companion read when work feels too fragmented.",
    pageCount: 296,
    progress: 100,
    status: "completed",
    rating: 4,
    isFavorite: false,
    createdAt: "2026-07-17T09:00:00.000Z",
    updatedAt: "2026-07-29T18:15:00.000Z",
  },
  {
    id: "book-pragmatic-programmer",
    title: "The Pragmatic Programmer",
    author: "Andrew Hunt",
    category: "Programming",
    description:
      "Timeless engineering advice about writing software that stays adaptable.",
    notes: "Keep revisiting this while building projects.",
    pageCount: 352,
    progress: 100,
    status: "completed",
    rating: 5,
    isFavorite: true,
    createdAt: "2026-07-14T09:00:00.000Z",
    updatedAt: "2026-07-31T08:00:00.000Z",
  },
  {
    id: "book-clean-code",
    title: "Clean Code",
    author: "Robert C. Martin",
    category: "Programming",
    description:
      "Opinionated lessons on readability, naming, and maintaining a healthy codebase.",
    notes: "Still in progress. Compare ideas with modern React conventions.",
    pageCount: 464,
    progress: 38,
    status: "reading",
    rating: 4,
    isFavorite: false,
    createdAt: "2026-07-12T09:00:00.000Z",
    updatedAt: "2026-08-02T06:45:00.000Z",
  },
  {
    id: "book-designing-data-intensive-applications",
    title: "Designing Data-Intensive Applications",
    author: "Martin Kleppmann",
    category: "Systems",
    description:
      "A deeper systems book on reliability, scale, and the tradeoffs behind modern data platforms.",
    notes: "Planned for the next serious long-form read.",
    pageCount: 616,
    progress: 0,
    status: "planned",
    rating: 0,
    isFavorite: false,
    createdAt: "2026-07-11T09:00:00.000Z",
    updatedAt: "2026-07-11T09:00:00.000Z",
  },
];
